version: "3.4"

services:
  database:
    image: mongo
    container_name: 'chat-mongo-container'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./backend:/home/node/app
      - ./backend/node_modules:/home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - database
    command: "npm run dev"

  frontend:
    build:
      context: ./frontend
      target: build
    restart: unless-stopped
    env_file: ./frontend/.env
    ports:
      - 80:80
      - 35729:35729 #livereload
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend
    command: > #we need to rebuild node-sass inside of the container first
      sh -c "node node_modules/node-sass/scripts/install.js &&
             npm run dev"

networks:
  app-network:
    driver: bridge
